from route import Route

def survivor_selection(population, offspring):
    """
       Selects the individuals with the highest fitness from the previous
       population and the offspring (mu + lambda) for the next generation.
       args:
           list : the previous population
           list : the offspring generated by this population
       returns:
           list : the population for the next generation
    """

    total_population = population + offspring
    total_population.sort(key=lambda x: x.get_fitness(), reverse=True)
    new_population = total_population(:len(population))

    return new_population
